import { 
  Client, 
  Container, 
  DashboardMetrics, 
  Task, 
  DocumentRecord,
  Organization 
} from "@demurrageos/shared-types";

export const MOCK_ORGANIZATION: Organization = {
  id: "org_apex_01",
  name: "Apex Logistics & Customs Clearance Ltd.",
  code: "APEX-BOM",
  role: "CHA",
};

export const MOCK_CLIENTS: Client[] = [
  {
    id: "client_bharat_01",
    organizationId: "org_apex_01",
    name: "Bharat Steel Corporation",
    code: "BSC-IND",
    aeoStatus: "AEO_T2",
    email: "shipping@bharatsteel.com",
    phone: "+91 22 6120 4000",
    activeContainersCount: 14,
    criticalRiskCount: 2,
    totalExposureINR: 245000,
  },
  {
    id: "client_zodiac_02",
    organizationId: "org_apex_01",
    name: "Zodiac Automotive Components",
    code: "ZAC-PUN",
    aeoStatus: "NONE",
    email: "import@zodiacauto.in",
    phone: "+91 20 2740 8890",
    activeContainersCount: 9,
    criticalRiskCount: 1,
    totalExposureINR: 185000,
  },
  {
    id: "client_titan_03",
    organizationId: "org_apex_01",
    name: "Titan Chemical Industries",
    code: "TCI-GUJ",
    aeoStatus: "AEO_T1",
    email: "supply@titanchem.co.in",
    phone: "+91 79 4000 1234",
    activeContainersCount: 12,
    criticalRiskCount: 0,
    totalExposureINR: 0,
  },
  {
    id: "client_sunbeam_04",
    organizationId: "org_apex_01",
    name: "Sunbeam Electronics Ltd",
    code: "SBE-DEL",
    aeoStatus: "NONE",
    email: "logistics@sunbeamelec.com",
    phone: "+91 11 4560 9090",
    activeContainersCount: 7,
    criticalRiskCount: 1,
    totalExposureINR: 88000,
  },
];

export const MOCK_CONTAINERS: Container[] = [
  {
    id: "cnt_msku_8294102",
    containerNumber: "MSKU8294102",
    clientId: "client_bharat_01",
    clientName: "Bharat Steel Corporation",
    organizationId: "org_apex_01",
    blNumber: "MAEU94820194",
    shippingLine: "Maersk Line India",
    vesselName: "MAERSK EINDHOVEN",
    voyageNumber: "2408W",
    portOfDischarge: "Nhava Sheva (JNPT / NSFT)",
    currentLocation: "Speedy CFS Terminal 2, Nhava Sheva",
    deliveryMode: "DPD_CFS",
    status: "CRITICAL",
    dischargedAt: "2026-09-04T08:30:00Z",
    twoClocks: {
      hasFallback: true,
      carrierClock: {
        basis: "Port Discharge Basis (Maersk Standard)",
        startDate: "2026-09-04T08:30:00Z",
        freeDaysTotal: 5,
        freeDaysRemaining: 0,
        daysOverdue: 5,
        isActive: true,
        expiryDate: "2026-09-09T08:30:00Z",
      },
      cfsClock: {
        basis: "CFS Ground Rent (Speedy CFS Post-Fallback)",
        startDate: "2026-09-08T14:15:00Z",
        freeDaysTotal: 3,
        freeDaysRemaining: 0,
        daysOverdue: 3,
        isActive: true,
        expiryDate: "2026-09-11T14:15:00Z",
      },
    },
    currentExposureINR: 145000,
    projectedExposureINR: 235000,
    charges: [
      {
        type: "DEMURRAGE",
        label: "Carrier Demurrage (Maersk 5 days overdue @ ₹14,000/day tier)",
        amount: 70000,
        currency: "INR",
        clockBasis: "Discharge Basis",
        daysBilled: 5,
        dailyRate: 14000,
      },
      {
        type: "GROUND_RENT",
        label: "CFS Ground Rent (Speedy CFS 3 days overdue @ ₹15,000/day tier)",
        amount: 45000,
        currency: "INR",
        clockBasis: "CFS Gate-In Basis",
        daysBilled: 3,
        dailyRate: 15000,
      },
      {
        type: "SHIFTING_CHARGE",
        label: "Yard Shifting Audit Target (Internal transfer fee)",
        amount: 12000,
        currency: "INR",
        clockBasis: "One-Time Assessment",
        daysBilled: 1,
        dailyRate: 12000,
        isAuditTarget: true,
      },
      {
        type: "STORAGE",
        label: "Port Terminal Storage",
        amount: 18000,
        currency: "INR",
        clockBasis: "Terminal Operator",
        daysBilled: 2,
        dailyRate: 9000,
      },
    ],
    risk: {
      level: "CRITICAL",
      totalScore: 88,
      urgencyScore: 28,
      customsScore: 25,
      pickupScore: 18,
      financialScore: 12,
      uncertaintyScore: 5,
      reasons: [
        "Free time expired 5 days ago; accumulating dual clocks (Carrier Demurrage + CFS Ground Rent)",
        "Delivery mode fallen back from DPD to CFS due to delivery order amendment delay",
        "Customs compliance alert: Novel HS Code declaration discrepancy flag raised",
        "Pickup transporter not confirmed: Ramesh Yadav pending acceptance",
      ],
      recommendedActions: [
        "Dispatch transporter confirmation token immediately to Mahalakshmi Transport",
        "Obtain re-issued DO from Maersk and clear outstanding terminal shifting charges",
        "Instruct field CHA executive to present Bill of Entry amendment at JNPT Custom House",
      ],
    },
    complianceSignals: [
      {
        id: "sig_01",
        containerId: "cnt_msku_8294102",
        signalType: "HS_CODE_NOVELTY",
        title: "Novel HS Code 7210.49.00 (Galvanized Steel)",
        score: 25,
        description: "First time client Bharat Steel is importing under this sub-heading in 12 months; increased inspection likelihood.",
        severity: "WARNING",
      },
      {
        id: "sig_02",
        containerId: "cnt_msku_8294102",
        signalType: "DOC_COMPLETENESS",
        title: "Delivery Order (DO) Re-issuance Pending",
        score: 20,
        description: "Carrier DO expired on Sept 9; new DO fee required before gate-out permit will be validated.",
        severity: "ALERT",
      },
    ],
    events: [
      {
        id: "evt_01",
        containerId: "cnt_msku_8294102",
        eventType: "CONTAINER_DISCHARGED",
        timestamp: "2026-09-04T08:30:00Z",
        location: "JNPT NSFT Terminal",
        source: "PORT_SYSTEM",
        description: "Vessel MAERSK EINDHOVEN discharged container to yard block 4C",
      },
      {
        id: "evt_02",
        containerId: "cnt_msku_8294102",
        eventType: "DELIVERY_ORDER_ISSUED",
        timestamp: "2026-09-05T11:00:00Z",
        location: "Maersk Line Agency Mumbai",
        source: "CARRIER_EDI",
        description: "Original Delivery Order issued with 5 free days",
      },
      {
        id: "evt_03",
        containerId: "cnt_msku_8294102",
        eventType: "DPD_TO_CFS_FALLBACK",
        timestamp: "2026-09-07T16:45:00Z",
        location: "JNPT DPD Terminal Gates",
        source: "PORT_SYSTEM",
        description: "Container DPD 48hr clearance window lapsed; automated routing transferred cargo to Speedy CFS",
      },
      {
        id: "evt_04",
        containerId: "cnt_msku_8294102",
        eventType: "CFS_GATE_IN",
        timestamp: "2026-09-08T14:15:00Z",
        location: "Speedy CFS Terminal 2",
        source: "CSV_IMPORT",
        description: "Container gated into Speedy CFS; CFS Ground Rent clock started",
      },
      {
        id: "evt_05",
        containerId: "cnt_msku_8294102",
        eventType: "CONTAINER_PICKUP_SCHEDULED",
        timestamp: "2026-09-13T10:00:00Z",
        location: "Apex Dispatch System",
        source: "EXTERNAL_CONFIRMATION",
        description: "Pickup assigned to Ramesh Yadav (Mahalakshmi Transport). Token dispatch initiated.",
      },
    ],
    openTasksCount: 2,
    updatedAt: "2026-09-14T06:00:00Z",
  },
  {
    id: "cnt_cmau_9182301",
    containerNumber: "CMAU9182301",
    clientId: "client_zodiac_02",
    clientName: "Zodiac Automotive Components",
    organizationId: "org_apex_01",
    blNumber: "CMAC99281726",
    shippingLine: "CMA CGM India",
    vesselName: "CMA CGM CHENNAI",
    voyageNumber: "109S",
    portOfDischarge: "Mundra Port (APSEZ)",
    currentLocation: "MICT Terminal Yard, Mundra",
    deliveryMode: "DPD_DIRECT",
    status: "WARNING",
    dischargedAt: "2026-09-10T04:15:00Z",
    twoClocks: {
      hasFallback: false,
      carrierClock: {
        basis: "Port Discharge Basis (CMA CGM Standard)",
        startDate: "2026-09-10T04:15:00Z",
        freeDaysTotal: 5,
        freeDaysRemaining: 1,
        daysOverdue: 0,
        isActive: true,
        expiryDate: "2026-09-15T04:15:00Z",
      },
    },
    currentExposureINR: 0,
    projectedExposureINR: 42000,
    charges: [],
    risk: {
      level: "HIGH",
      totalScore: 68,
      urgencyScore: 22,
      customsScore: 20,
      pickupScore: 16,
      financialScore: 5,
      uncertaintyScore: 5,
      reasons: [
        "Free time expires in under 24 hours at Mundra MICT",
        "Out of Charge (OOC) received but delivery order not endorsed for DPD direct gate-out",
        "Direct transporter vehicle details not submitted to terminal gate portal",
      ],
      recommendedActions: [
        "Punch vehicle number in Mundra ODEX portal to secure direct DPD gate-pass",
        "Alert client Zodiac Automotive to release electronic payment for terminal handling",
      ],
    },
    complianceSignals: [
      {
        id: "sig_03",
        containerId: "cnt_cmau_9182301",
        signalType: "DOC_COMPLETENESS",
        title: "Terminal Gate Pass Endorsement Missing",
        score: 18,
        description: "DPD Direct requires gate appointment token 6 hours prior to truck arrival.",
        severity: "WARNING",
      },
    ],
    events: [
      {
        id: "evt_11",
        containerId: "cnt_cmau_9182301",
        eventType: "CONTAINER_DISCHARGED",
        timestamp: "2026-09-10T04:15:00Z",
        location: "Mundra MICT",
        source: "PORT_SYSTEM",
        description: "Discharged from CMA CGM CHENNAI to DPD stack area",
      },
      {
        id: "evt_12",
        containerId: "cnt_cmau_9182301",
        eventType: "CUSTOMS_OUT_OF_CHARGE",
        timestamp: "2026-09-12T14:30:00Z",
        location: "Mundra Customs",
        source: "MANUAL_ENTRY",
        description: "Bill of Entry passed with Out of Charge order",
      },
    ],
    openTasksCount: 1,
    updatedAt: "2026-09-14T05:30:00Z",
  },
  {
    id: "cnt_medu_4910283",
    containerNumber: "MEDU4910283",
    clientId: "client_bharat_01",
    clientName: "Bharat Steel Corporation",
    organizationId: "org_apex_01",
    blNumber: "MSCU01928472",
    shippingLine: "MSC Mediterranean Shipping",
    vesselName: "MSC BEATRICE",
    voyageNumber: "402E",
    portOfDischarge: "Chennai Port (CITPL)",
    currentLocation: "Sattva CFS, Ponneri, Chennai",
    deliveryMode: "CFS",
    status: "CRITICAL",
    dischargedAt: "2026-09-02T12:00:00Z",
    twoClocks: {
      hasFallback: false,
      carrierClock: {
        basis: "Carrier Discharge Clock (MSC Standard 7 days)",
        startDate: "2026-09-02T12:00:00Z",
        freeDaysTotal: 7,
        freeDaysRemaining: 0,
        daysOverdue: 5,
        isActive: true,
        expiryDate: "2026-09-09T12:00:00Z",
      },
      cfsClock: {
        basis: "CFS Ground Rent (Sattva CFS 3 free days)",
        startDate: "2026-09-05T09:00:00Z",
        freeDaysTotal: 3,
        freeDaysRemaining: 0,
        daysOverdue: 6,
        isActive: true,
        expiryDate: "2026-09-08T09:00:00Z",
      },
    },
    currentExposureINR: 100000,
    projectedExposureINR: 180000,
    charges: [
      {
        type: "DEMURRAGE",
        label: "MSC Carrier Demurrage (5 days @ ₹11,000)",
        amount: 55000,
        currency: "INR",
        clockBasis: "Discharge Basis",
        daysBilled: 5,
        dailyRate: 11000,
      },
      {
        type: "GROUND_RENT",
        label: "Sattva CFS Ground Rent (6 days @ ₹7,500)",
        amount: 45000,
        currency: "INR",
        clockBasis: "CFS Gate-In Basis",
        daysBilled: 6,
        dailyRate: 7500,
      },
    ],
    risk: {
      level: "CRITICAL",
      totalScore: 92,
      urgencyScore: 30,
      customsScore: 28,
      pickupScore: 16,
      financialScore: 12,
      uncertaintyScore: 6,
      reasons: [
        "Demurrage and ground rent clocks both accumulating heavily at Chennai",
        "Bill of Entry documentation query pending customs officer signature",
      ],
      recommendedActions: [
        "Expedite Customs assessment query response at Chennai Port Customs House",
        "Lock in delivery order extension to avoid escalating tier charges",
      ],
    },
    complianceSignals: [
      {
        id: "sig_04",
        containerId: "cnt_medu_4910283",
        signalType: "DOC_COMPLETENESS",
        title: "Bill of Entry Query Raised by Appraising Group 7",
        score: 28,
        description: "Valuation clarification demanded for invoice line item 4.",
        severity: "ALERT",
      },
    ],
    events: [
      {
        id: "evt_21",
        containerId: "cnt_medu_4910283",
        eventType: "CONTAINER_DISCHARGED",
        timestamp: "2026-09-02T12:00:00Z",
        location: "Chennai CITPL",
        source: "PORT_SYSTEM",
        description: "Discharged to terminal yard",
      },
      {
        id: "evt_22",
        containerId: "cnt_medu_4910283",
        eventType: "CFS_GATE_IN",
        timestamp: "2026-09-05T09:00:00Z",
        location: "Sattva CFS Chennai",
        source: "PORT_SYSTEM",
        description: "En-route transfer to Sattva CFS completed",
      },
      {
        id: "evt_23",
        containerId: "cnt_medu_4910283",
        eventType: "CUSTOMS_EXAM_ORDERED",
        timestamp: "2026-09-08T15:20:00Z",
        location: "Sattva CFS Customs Shed",
        source: "MANUAL_ENTRY",
        description: "Appraising group ordered 100% physical examination of cargo",
      },
    ],
    openTasksCount: 1,
    updatedAt: "2026-09-14T05:00:00Z",
  },
  {
    id: "cnt_hlxu_7102948",
    containerNumber: "HLXU7102948",
    clientId: "client_titan_03",
    clientName: "Titan Chemical Industries",
    organizationId: "org_apex_01",
    blNumber: "HLCU00192841",
    shippingLine: "Hapag-Lloyd India",
    vesselName: "VALPARAISO EXPRESS",
    voyageNumber: "2431E",
    portOfDischarge: "Nhava Sheva (JNPT / GTI)",
    currentLocation: "GTI DPD Direct Buffer Yard",
    deliveryMode: "DPD_DIRECT",
    status: "ON_TRACK",
    dischargedAt: "2026-09-12T18:00:00Z",
    twoClocks: {
      hasFallback: false,
      carrierClock: {
        basis: "Carrier Discharge Clock (Hapag-Lloyd AEO 14 days)",
        startDate: "2026-09-12T18:00:00Z",
        freeDaysTotal: 14,
        freeDaysRemaining: 12,
        daysOverdue: 0,
        isActive: true,
        expiryDate: "2026-09-26T18:00:00Z",
      },
    },
    currentExposureINR: 0,
    projectedExposureINR: 0,
    charges: [],
    risk: {
      level: "LOW",
      totalScore: 15,
      urgencyScore: 4,
      customsScore: 4,
      pickupScore: 4,
      financialScore: 0,
      uncertaintyScore: 3,
      reasons: [
        "12 free days remaining due to Client AEO-T1 status extended free-time agreement",
        "Customs Out of Charge cleared on arrival",
      ],
      recommendedActions: [
        "Pickup scheduled within standard 48hr window",
      ],
    },
    complianceSignals: [
      {
        id: "sig_05",
        containerId: "cnt_hlxu_7102948",
        signalType: "AEO_ACP_STATUS",
        title: "AEO Tier 1 Green Channel Privilege",
        score: 0,
        description: "Zero physical inspection ordered. Direct port clearance expedited.",
        severity: "INFO",
      },
    ],
    events: [
      {
        id: "evt_31",
        containerId: "cnt_hlxu_7102948",
        eventType: "CONTAINER_DISCHARGED",
        timestamp: "2026-09-12T18:00:00Z",
        location: "GTI Terminal JNPT",
        source: "PORT_SYSTEM",
        description: "Discharged to GTI DPD yard",
      },
      {
        id: "evt_32",
        containerId: "cnt_hlxu_7102948",
        eventType: "CUSTOMS_OUT_OF_CHARGE",
        timestamp: "2026-09-13T09:15:00Z",
        location: "JNPT Custom House",
        source: "PORT_SYSTEM",
        description: "Direct OOC granted via automated Risk Management System (RMS)",
      },
    ],
    openTasksCount: 0,
    updatedAt: "2026-09-14T04:00:00Z",
  },
  {
    id: "cnt_cosu_6201948",
    containerNumber: "COSU6201948",
    clientId: "client_sunbeam_04",
    clientName: "Sunbeam Electronics Ltd",
    organizationId: "org_apex_01",
    blNumber: "COSU61029481",
    shippingLine: "COSCO Shipping India",
    vesselName: "COSCO PRIDE",
    voyageNumber: "084W",
    portOfDischarge: "Nhava Sheva (JNPT / BMCT)",
    currentLocation: "JWC CFS Panvel, Navi Mumbai",
    deliveryMode: "CFS",
    status: "CRITICAL",
    dischargedAt: "2026-09-06T10:00:00Z",
    twoClocks: {
      hasFallback: false,
      carrierClock: {
        basis: "Carrier Discharge Clock (COSCO 5 days)",
        startDate: "2026-09-06T10:00:00Z",
        freeDaysTotal: 5,
        freeDaysRemaining: 0,
        daysOverdue: 3,
        isActive: true,
        expiryDate: "2026-09-11T10:00:00Z",
      },
      cfsClock: {
        basis: "CFS Ground Rent (JWC CFS)",
        startDate: "2026-09-08T16:00:00Z",
        freeDaysTotal: 3,
        freeDaysRemaining: 0,
        daysOverdue: 3,
        isActive: true,
        expiryDate: "2026-09-11T16:00:00Z",
      },
    },
    currentExposureINR: 88000,
    projectedExposureINR: 154000,
    charges: [
      {
        type: "DEMURRAGE",
        label: "COSCO Demurrage (3 days @ ₹16,000)",
        amount: 48000,
        currency: "INR",
        clockBasis: "Discharge Basis",
        daysBilled: 3,
        dailyRate: 16000,
      },
      {
        type: "GROUND_RENT",
        label: "JWC CFS Ground Rent (3 days @ ₹10,000)",
        amount: 30000,
        currency: "INR",
        clockBasis: "CFS Gate-In Basis",
        daysBilled: 3,
        dailyRate: 10000,
      },
      {
        type: "STORAGE",
        label: "Hazardous Chemical Yard Storage Surcharge",
        amount: 10000,
        currency: "INR",
        clockBasis: "Special Handling",
        daysBilled: 1,
        dailyRate: 10000,
      },
    ],
    risk: {
      level: "CRITICAL",
      totalScore: 85,
      urgencyScore: 24,
      customsScore: 26,
      pickupScore: 15,
      financialScore: 12,
      uncertaintyScore: 8,
      reasons: [
        "Free-time expired; dual demurrage + ground rent running at Panvel",
        "Valuation consistency warning: invoice unit price 38% lower than 6-month historical import average",
      ],
      recommendedActions: [
        "Upload manufacturer price list to explain valuation variance to Customs appraiser",
      ],
    },
    complianceSignals: [
      {
        id: "sig_06",
        containerId: "cnt_cosu_6201948",
        signalType: "VALUATION_CONSISTENCY",
        title: "Valuation Variance Warning (-38%)",
        score: 26,
        description: "Reported value $4.20/kg compared to benchmark $6.80/kg for HS 8504.40.",
        severity: "ALERT",
      },
    ],
    events: [
      {
        id: "evt_41",
        containerId: "cnt_cosu_6201948",
        eventType: "CONTAINER_DISCHARGED",
        timestamp: "2026-09-06T10:00:00Z",
        location: "BMCT Terminal JNPT",
        source: "PORT_SYSTEM",
        description: "Discharged from COSCO PRIDE",
      },
      {
        id: "evt_42",
        containerId: "cnt_cosu_6201948",
        eventType: "CFS_GATE_IN",
        timestamp: "2026-09-08T16:00:00Z",
        location: "JWC CFS Panvel",
        source: "CSV_IMPORT",
        description: "Transfer to CFS completed",
      },
    ],
    openTasksCount: 1,
    updatedAt: "2026-09-14T03:30:00Z",
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "tsk_01_pickup_ramesh",
    containerId: "cnt_msku_8294102",
    containerNumber: "MSKU8294102",
    clientId: "client_bharat_01",
    clientName: "Bharat Steel Corporation",
    title: "Schedule container pickup with Mahalakshmi Transport",
    description: "Coordinate container gate-out from Speedy CFS Terminal 2 to Bharat Steel Taloja Plant.",
    status: "ASSIGNED",
    assigneeType: "EXTERNAL",
    assigneeName: "Ramesh Yadav",
    assigneeContact: "+91 98201 12345",
    externalToken: "tok_trk_9182a47e",
    tokenExpiry: "2026-09-17T12:00:00Z",
    dueDate: "2026-09-14T18:00:00Z",
    createdAt: "2026-09-13T10:00:00Z",
  },
  {
    id: "tsk_02_do_reissue",
    containerId: "cnt_msku_8294102",
    containerNumber: "MSKU8294102",
    clientId: "client_bharat_01",
    clientName: "Bharat Steel Corporation",
    title: "Obtain re-issued Delivery Order (DO) from Maersk",
    description: "Pay DO re-issuance fee and upload updated DO to terminal portal to lift block.",
    status: "OPEN",
    assigneeType: "INTERNAL",
    assigneeName: "Priya Sharma (Operations Executive)",
    dueDate: "2026-09-14T15:00:00Z",
    createdAt: "2026-09-13T11:30:00Z",
  },
  {
    id: "tsk_03_mundra_appointment",
    containerId: "cnt_cmau_9182301",
    containerNumber: "CMAU9182301",
    clientId: "client_zodiac_02",
    clientName: "Zodiac Automotive Components",
    title: "Generate DPD Direct Gate Token on Mundra ODEX",
    description: "Free time expires in 24 hours. Submit truck number for priority DPD gate-out.",
    status: "OPEN",
    assigneeType: "INTERNAL",
    assigneeName: "Aniket Verma (Field Associate)",
    dueDate: "2026-09-14T20:00:00Z",
    createdAt: "2026-09-14T02:00:00Z",
  },
  {
    id: "tsk_04_chennai_query",
    containerId: "cnt_medu_4910283",
    containerNumber: "MEDU4910283",
    clientId: "client_bharat_01",
    clientName: "Bharat Steel Corporation",
    title: "Clear Customs Group 7 Valuation Clarification Query",
    description: "Submit manufacturer certificate of analysis and transaction value proof at Chennai Customs House.",
    status: "OPEN",
    assigneeType: "INTERNAL",
    assigneeName: "Senthil Nathan (Customs Counsel)",
    dueDate: "2026-09-15T11:00:00Z",
    createdAt: "2026-09-13T14:00:00Z",
  },
];

export const MOCK_DOCUMENTS: DocumentRecord[] = [
  {
    id: "doc_do_msku_8294",
    containerId: "cnt_msku_8294102",
    documentType: "DELIVERY_ORDER",
    filename: "MAERSK_DO_MAEU94820194.pdf",
    uploadDate: "2026-09-05T11:00:00Z",
    fileSize: 342000,
    status: "REVIEWED",
    extractedFields: {
      consignee: {
        label: "Consignee Name",
        value: "BHARAT STEEL CORPORATION PVT LTD",
        confidence: 0.98,
        flaggedForReview: false,
      },
      blNumber: {
        label: "Bill of Lading Number",
        value: "MAEU94820194",
        confidence: 0.99,
        flaggedForReview: false,
      },
      containerNumber: {
        label: "Container Number",
        value: "MSKU8294102",
        confidence: 0.99,
        flaggedForReview: false,
      },
      freeDaysGranted: {
        label: "Free Days Granted",
        value: 5,
        confidence: 0.92,
        flaggedForReview: false,
      },
      deliveryOrderExpiry: {
        label: "DO Valid Upto",
        value: "2026-09-09",
        confidence: 0.89,
        flaggedForReview: true,
      },
      dischargePort: {
        label: "Discharge Port Code",
        value: "INNSA (Nhava Sheva)",
        confidence: 0.97,
        flaggedForReview: false,
      },
    },
  },
  {
    id: "doc_boe_msku_8294",
    containerId: "cnt_msku_8294102",
    documentType: "BILL_OF_ENTRY",
    filename: "BOE_7891204_04092026.pdf",
    uploadDate: "2026-09-06T09:30:00Z",
    fileSize: 520000,
    status: "EXTRACTED",
    extractedFields: {
      billOfEntryNumber: {
        label: "Bill of Entry Number",
        value: "7891204",
        confidence: 0.99,
        flaggedForReview: false,
      },
      hsCode: {
        label: "Declared HS Code",
        value: "7210.49.00",
        confidence: 0.94,
        flaggedForReview: true, // Novel HS code trigger
      },
      assessableValueINR: {
        label: "Assessable Value (INR)",
        value: 4850000,
        confidence: 0.96,
        flaggedForReview: false,
      },
      dutyAmountINR: {
        label: "Total Customs Duty (INR)",
        value: 1212500,
        confidence: 0.95,
        flaggedForReview: false,
      },
    },
  },
];

export function getMockDashboardMetrics(clientId: string | "ALL"): DashboardMetrics {
  const filteredContainers = clientId === "ALL" 
    ? MOCK_CONTAINERS 
    : MOCK_CONTAINERS.filter(c => c.clientId === clientId);

  const totalExposure = filteredContainers.reduce((acc, c) => acc + c.currentExposureINR, 0);
  const criticalExposure = filteredContainers
    .filter(c => c.status === "CRITICAL")
    .reduce((acc, c) => acc + c.currentExposureINR, 0);

  const atRiskCount = filteredContainers.filter(c => c.status === "CRITICAL" || c.status === "WARNING").length;

  const relevantTasks = clientId === "ALL"
    ? MOCK_TASKS
    : MOCK_TASKS.filter(t => t.clientId === clientId);

  return {
    totalContainers: filteredContainers.length,
    atRiskContainers: atRiskCount,
    criticalExposureINR: criticalExposure,
    totalExposureINR: totalExposure,
    preventableExposureINR: Math.round(totalExposure * 0.75), // 75% preventable with early interventions
    activeClientsCount: clientId === "ALL" ? MOCK_CLIENTS.length : 1,
    recentTasks: relevantTasks,
    urgentAlerts: [
      {
        id: "alt_01",
        containerId: "cnt_msku_8294102",
        containerNumber: "MSKU8294102",
        clientName: "Bharat Steel Corporation",
        type: "DPD_FALLBACK" as const,
        message: "Container DPD window lapsed; transferred to Speedy CFS. Two-clock ground rent active.",
        severity: "CRITICAL" as const,
        timestamp: "2026-09-07T16:45:00Z",
      },
      {
        id: "alt_02",
        containerId: "cnt_cmau_9182301",
        containerNumber: "CMAU9182301",
        clientName: "Zodiac Automotive Components",
        type: "FREE_TIME_EXPIRING" as const,
        message: "Free time expires in under 24 hours at Mundra MICT terminal.",
        severity: "WARNING" as const,
        timestamp: "2026-09-14T04:15:00Z",
      },
    ].filter(a => clientId === "ALL" || MOCK_CONTAINERS.find(c => c.id === a.containerId)?.clientId === clientId),
  };
}
